version: 2

models:
  - name: dim_customer_orders
    description: This table stores every customer's ID and their order IDs and order dates.

    columns:
      - name: customer_id
        description: Unique identifier for a customer.

      - name: order_date
        description: Date that the order was placed

      - name: order_id
        description: Unique identifier for an order.
        tests:
          - unique
      
      - name: order_status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: customer_first_name
        description: Customer's first name. 

      - name: customer_last_name_initial
        description: Customer's last name initial.
  
  - name: dim_order_payments
    description: This table stores order IDs and associated payment information.

    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: payment_date
        description: Date of payment.
        tests:
          - not_null
      
      - name: total_amount_paid
        description: Total amount paid for order.
        tests:
          - not_null


